import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../../../styles/Home.module.css'
import { useRouter } from 'next/router';

const Basic = () => {
    const router = useRouter()
    const { level } = router.query

    return (
        <div className={styles.container}>
            <Head>
                <title>Basic</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.main}>
                    
                    {level}
                </div>
            </main>

        </div>
    );
}

export default Basic;
