import React , {useEffect, useState }from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../../../styles/Home.module.css'
import { useRouter } from 'next/router';
import {operators, Resultados} from '../../../utils/data'
import ButtonDefault from '../../../components/Button/ButtonDefault';
import Keyboard from '../../../components/Keyboard'


const Basic = () => {
    const router = useRouter()
    const { level } = router.query
    const [operatorSelect, setOperatorSelect] = useState();
    const [expression, setExpression] = useState('');
    const [number1, setNumber1] = useState(0);
    const [number2, setNumber2] = useState(0);
    const [resp, setResp] = useState('');
    const [value, setValue] = useState('');



    useEffect(() => {
        Resultados.splice(0, Resultados.length);
        getNum();
        
        
    }, []);

    function getNum() {
        
        let operator=Math.floor(Math.random() * (operators.length-1));
        let num1=getNumber1(20);
        let num2=getRandomIntInclusive(0,num1);
        setNumber1(num1);
        setNumber2(num2);
        setOperatorSelect(operators[operator]);
        setExpression(num1+operator+num2)
        setResp('');
        
    }

    function getNumber1(num){

        let number=Math.floor(Math.random() * (num));
        return number+1;

    }

    function getRandomIntInclusive(min, max) {

        return Math.floor(Math.random() * (max - min + 1) + min);
    }

    function verificar() {
        if (resp!=''){
            let val = 0;
            switch (operatorSelect) {
                case '+':
                    setValue(number1 + number2);
                    val = number1 + number2;
                    break;
                case '-':
                    setValue(number1 - number2);
                    val = number1 - number2;
                    break;
                case 'x':
                    setValue(number1 * number2);
                    val = number1 * number2;
                    break;
                case '÷':
                    setValue(number1 / number2);
                    val = number1 / number2;
                    break;
                default:
                    break;
            }
            
            let tempExp = {
                expression : `${number1} ${operatorSelect} ${number2} = ${resp}`,
                resp: `${resp}`,
                value : `${val}`
            }

            Resultados.push(tempExp);
            console.log(Resultados);
            getNum();
        }
        

    }

    function click(params) {
        let temp = resp;
        setResp(temp+params);
    }
    function del(params) {
        let temp = resp;
        setResp(temp.slice(0, -1));
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Basic</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className='d-flex gap-5 justify-content-center '>
                    <div className='container gap-5 justify-content-center me-5'>
                        <div className='row'>
                            <div className="d-flex justify-content-center">
                                <h2 >{`${number1} ${operatorSelect} ${number2}`}</h2>
                            </div>
                        </div>
                        <div className='row'>
                            <div className={"col border bg-light m-2"}>
                                <h2 className={styles.custom}>{resp}</h2>
                            </div>
                        </div>
                    </div>
                    
                </div>

                <div>
                    <Keyboard click={click} verificar={verificar} del={del}/>
                </div>
            </main>

        </div>
    );
}

export default Basic;
