import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css'

const Basic = () => {
    const LevelList =[
        1,2,3,4,5
    ]
    const caminho = 'basic/'
    return (
        <div className={styles.container}>
            <Head>
                <title>Basic</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.main}>
                    <p>Level : </p>
                    {
                        LevelList.map(nivel => <Link key={nivel} href={caminho+nivel} target="_self" ><a ><div key={nivel} ><p className='btn btn-outline-primary mt-2 me-2'>{nivel}</p></div></a></Link>)
                    }
                </div>
                <div>

                </div>
            </main>

        </div>
    );
}

export default Basic;
