import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ButtonDefault from '../components/Button/ButtonDefault' 

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Math Expressions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.line}>
          <span className='fs-5'> Basic </span>
          <a href='./basic' className='btn btn-outline-primary mt-2 me-2'>+ - x ÷</a>
        </div>
        <div className={styles.line}>
          <span className='fs-5'>Comparators</span>
          <a href='./basic' className='btn btn-outline-primary mt-2 me-2'>{`> = <`}</a>
        </div>


      </main>
    </div>
  )
}
